config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  devise_for :users
  get 'about' => "homes#about"
  resources :posts
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :post_tags, through: :taggings, source: :tag
  belongs_to :user

  def save_with(tag_names)
    #複数のSQL処理を一つのトランザクションにまとめる
    #タグとPostが同時に作成される処理のため、複数のSQLが走るから
    ActiveRecord::Base.transaction do
      #作成するタグの値がすでに存在していればそのタグを返し、存在していなければインスタンス化するメソッド
      #タグの名前を重複するのを防ぐことができる
      self.post_tags = tag_names.map { |name| Tag.find_or_initialize_by(name: name.strip) }
      save!
    end
    true

  rescue StandardError
    false
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :tagged_posts, through: :taggings, source: :post

  validates :name, presence: true, uniqueness: true
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :post
  belongs_to :tag

  validates :tag_id, uniqueness: { scope: :post_id }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    about_path
  end

  def after_sign_out_path_for(resource)
    about_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save!
      redirect_to posts_path
    else
      render :new
    end
  end

  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to post_path(@post.id)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

  def tag_names
    params[:post][:tag_names].split(' ').uniq
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all.order(created_at: :desc)
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(created_at: :desc)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id), notice: "プロフィールが更新されました。"
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
About

app/views/homes/top.html.erb
<div class= "container-fluid">
  <div class="top-image d-flex flex-column justify-content-center align-items-center">
    <h1 class="title">トップページ</h1>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TagNoGem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if user_signed_in? %>
        <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        <li><%= link_to "新規投稿", new_post_path %></li>
        <li><%= link_to "投稿一覧", posts_path %></li>
        <li><%= link_to "ユーザー一覧", users_path %></li>
      <% else %>
        <li><%= link_to "新規登録", new_user_registration_path %></li>
        <li><%= link_to "ログイン", new_user_session_path %></li>
      <% end %>
    </header>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="row mt-5">
  <div class="col-6 offset-3">
    <h2 class="text-center mb-4"><i class="fas fa-user-edit"></i>投稿内容編集</h2>
    <%= form_with model: @post, url: post_path(@post.id), method: :patch do |f| %>

      <div class="form-group">
        <label for="title">タイトル</label>
        <%= f.text_field :title, autofocus: true, placeholder: "30文字以内で記入してください", class: "form-control" %>
      </div>
      <div class="form-group">
        <label for="caption">投稿内容</label>
        <%= f.text_area :body, placeholder: "400文字以内で記入してください", class: "form-control" %>
      </div>

    <%= f.submit '変更を保存する', class: "btn btn-lg btn-primary btn-block mb-3" %>
  <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10 mt-5">
    <h2><i class="fas fa-handshake"></i>投稿一覧ページ</h2>
    <% @posts.each do |post| %>
      <div>
        <%= post.user.name %><br>
        <%= link_to post_path(post.id) do %>
          <%= post.title %>
        <% end %>
        <p>投稿日：<%= post.created_at.strftime('%Y/%m/%d %H:%M') %></p>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <h2 class="text-dark bg-light p-4 mb-0"><i class="fas fa-pen"></i>新規投稿</h2>
        <div class="form-body p-4">
          <% if @post.errors.any? %>
            <%= @post.errors.count %>件のエラーが発生しました
            <ul>
              <% @post.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
            </ul>
          <% end %>
          <%= form_with model: @post do |f| %>
            <h4 class="form-group" >
              <%= f.label :title, "タイトル" %>
              <%= f.text_field :title, class:"form-control" %>
            </h4>
            <h4 class="form-group">
              <%= f.label :body, "内容" %>
              <%= f.text_area :body, class:"form-control", rows:"6" %>
            </h4>
            <div class="form-group">
              <%= f.label :tag_names, "タグ名" %>
              <div class="chips">
                <%= f.text_field :tag_names, class: 'form-control', placeholder: '空白スペースで区切って入力してください' %>
              </div>
            </div>
            <div class="form-group">
              <%= f.submit '投稿', class: "btn btn-lg btn-block btn-info mt-4" %>
            </div>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10 mt-5">
      <h2><i class="fab fa-readme"></i>投稿詳細</h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="col-3">投稿ユーザー</th>
            <td class="col-9"><%= link_to user_path(@post.user.id) do %><%= @post.user.name %><% end %></td>
          </tr>
          <tr>
            <th class="col-3">投稿タイトル</th>
            <td class="col-9"><%= @post.title %></td>
          </tr>
          <tr>
            <th class="col-3">投稿内容</th>
            <td class="col-9"><%= @post.body %></td>
          </tr>
          <tr>
            <th class="col-3">投稿日時</th>
            <td class="col-9"><%= @post.created_at.strftime('%Y/%m/%d %H:%M') %></td>
          </tr>
          <tr>
            <th class="col-3">更新日時</th>
            <td class="col-9"><%= @post.updated_at.strftime('%Y/%m/%d %H:%M') %></td>
          </tr>
        </tbody>
      </table>

      <div class= "d-flex justify-content-center my-5">
        <% if @post.user == current_user %>
          <%= link_to "編集する", edit_post_path(@post.id), class: "btn btn btn-secondary" %>
          <%= link_to "削除する", post_path(@post.id), class: "btn btn btn-danger", method: :delete, "data-confirm" => "本当に削除しますか？" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10 mt-5">
      <h2><i class="fas fa-users" %></i>ユーザー一覧</h2>
        <table class="table text-center">
        <% @users.each do |user| %>
          <tr>
            <td>
              <%= link_to user_path(user) do %>
                <%= user.name %>
              <% end %>
            </td>
          </tr>
        <% end %>
        </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10 mt-5">
      <% if current_user == @user %>
        <h2><i class="fas fa-address-card"></i>マイページ</h2>
      <% else %>
        <h2><i class="fas fa-user"></i>プロフィール</h2>
      <% end %>
    <div class="text-center">
      <div>
        <h4><%= @user.name %></h4>
      </div>
      <div>
        <% if (@user == current_user) && !(@user.name == "GuestUser") %>
          <p><%= link_to "プロフィール編集", edit_user_path(current_user.id), class: "btn btn btn-secondary" %></p>
        <% end %>
      </div>
    </div>
   </div>
  </div>
</div>